export const userTypes = {
    SET_INPUT: "SET_INPUT",
    FETCH_USERS: "FETCH_USERS",

    POST_PET_START: "POST_PET_START",
    POST_PET_SUCCESS: "POST_PET_SUCCESS",
    POST_PET_FAIL: "POST_PET_FAIL"
}