export const detailTypes = {
    
    DETAIL_IMAGES_SUCCESS: "DETAIL_IMAGES_SUCCESS",
    DETAIL_SHELTER_SUCCESS: "DETAIL_SHELTER_SUCCESS",
    DETAIL_START: "DETAIL_START",
    DETAIL_FAIL: "DETAIL_FAIL"
}