export const authTypes = {
    
    SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
    SIGNIN_ERROR: "SIGNIN_ERROR",
    SIGNOUT_SUCCESS: "SIGNOUT_SUCCESS",
    SIGNOUT_ERROR: "SIGNOUT_ERROR",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_ERROR: "REGISTER_ERROR"
}

