export const petsTypes = {
    SET_SEARCH_INPUTS: "SET_SEARCH_INPUTS",
    CLEAR_SEARCH_RESULTS: "CLEAR_SEARCH_RESULTS",
    FETCH_USERS: "FETCH_USERS",
    SEARCH_PETS_START: "SEARCH_PETS_START",
    SEARCH_PETS_SUCCESS: "SEARCH_PETS_SUCCESS",
    SEARCH_PETS_FAIL: "SEARCH_PETS_FAIL",
    SEARCH_PET_SUCCESS: "SEARCH_PET_SUCCESS"
}