export const petsTypes = {
    
    SEARCH_PETS_START: "SEARCH_PETS_START",
    SEARCH_PETS_SUCCESS: "SEARCH_PETS_SUCCESS",
    SEARCH_PETS_AND_COUNT_SUCCESS: "SEARCH_PETS_AND_COUNT_SUCCESS",
    SEARCH_PETS_FAIL: "SEARCH_PETS_FAIL",
    SEARCH_PETS_UPDATE_FILTER: "SEARCH_PETS_UPDATE_FILTER"
}