export const spotLightTypes = {
    
    SEARCH_SPOTLIGHT_START: "SEARCH_SPOTLIGHT_START",
    SEARCH_SPOTLIGHT_SUCCESS: "SEARCH_SPOTLIGHT_SUCCESS",
    SEARCH_SPOTLIGHT_FAIL: "SEARCH_SPOTLIGHT_FAIL"
}